# Nginx

services:
  nginx:
    image: nginx:stable
    container_name: web_server
    # network_mode: "host"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/ssl/certs
    restart: unless-stopped
    networks:
      - dockernet

networks:
  dockernet:
    external: true