services:
  nginx:
    image: nginx
    volumes:
    - ./templates:/etc/nginx/templates
    ports:
    - "80:80"
    - "443:443"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
    - NGINX_PORT=443

networks:
  dockernet:
    external: true