# StackUI
services:
    webapp:
      container_name: stackui
      build: .
      ports:
        - "3000:3000" # Maps host port 3000 → container port 3000
      restart: unless-stopped
      environment:
        - NODE_ENV=production
      networks:
      - dockernet

networks:
  dockernet:
    external: true